spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@182.237.126.19:1521:XE
    username: F2211JDEVELOPER#TEAM2
    password: F2211JDEVELOPER#TEAM2  profiles:    include:    - aws
    - credentials
logging:
  level:
    jdbc:
      sqlonly: info
      sqltiming: off
      resultsettable: info
      audit: off
      resultset: off
      connection: off
      
